[package]
name = "DenoDig"
version = "1.2.0"
edition = "2021"

[workspace]

[dependencies]
tokio = { version = "1.0.0", features = ["rt-multi-thread"]}
clap = { version = "4.5.20", features = ["derive"] }
deno-dig-lib = { path = "deno-dig-lib" }

