[package]
name = "DenoDig"
version = "1.1.0"
edition = "2021"

[workspace]

[dependencies]
tokio = { version = "1.0.0" }
clap = { version = "4.5.20", features = ["derive"] }
deno-dig-lib = { path = "deno-dig-lib" }

